Vagrant.configure("2") do |config|
  # Настройки SSH для автоматической вставки ключа
  config.ssh.private_key_path = ["~/.ssh/id_ed25519"]
  config.ssh.insert_key = true
  config.ssh.forward_agent = false  # обычно не нужен, если не используете SSH-agent
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  # Синхронизация папок и провайдер (как у вас)
  config.vm.synced_folder ".", "/home/vagrant",
    owner: "vagrant",
    group: "vagrant",
    mount_options: ["dmode=775", "fmode=664"]

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end



  # Менеджер
  config.vm.define "manager01" do |manager|
    manager.vm.box = "ubuntu2204-local"
    manager.vm.hostname = "manager01"
    manager.vm.network "private_network", ip: "192.168.56.10"
    manager.vm.network "forwarded_port", guest: 8081, host: 8081
    manager.vm.network "forwarded_port", guest: 8087, host: 8087
    manager.vm.network "forwarded_port", guest: 9000, host: 9000
    # Установка Docker и инициализация Swarm
    manager.vm.provision "shell", path: "scripts/install_docker.sh"
    manager.vm.provision "shell", path: "scripts/init_swarm_manager.sh"
  end

  # Worker 1
  config.vm.define "worker01" do |worker|
    worker.vm.box = "ubuntu2204-local"
    worker.vm.hostname = "worker01"
    worker.vm.network "private_network", ip: "192.168.56.11"
    worker.vm.network "forwarded_port", guest: 8082, host: 8082
    
    # Установка Docker и присоединение к Swarm
    worker.vm.provision "shell", path: "scripts/install_docker.sh"
    worker.vm.provision "shell", path: "scripts/join_swarm_worker.sh"
     
  end

  # Worker 2
config.vm.define "worker02" do |worker|
    worker.vm.box = "ubuntu2204-local"
    worker.vm.hostname = "worker02"
    worker.vm.network "private_network", ip: "192.168.56.12"
    worker.vm.network "forwarded_port", guest: 8083, host: 8083
    
    # Установка Docker и присоединение к Swarm
    worker.vm.provision "shell", path: "scripts/install_docker.sh"
    worker.vm.provision "shell", path: "scripts/join_swarm_worker.sh"
     
  end
end
